#define TK_SEMI                            1
#define TK_CREATE                          2
#define TK_TABLE                           3
#define TK_LP                              4
#define TK_RP                              5
#define TK_COMMA                           6
#define TK_ID                              7
#define TK_STRING                          8
#define TK_CONSTRAINT                      9
#define TK_DEFAULT                        10
#define TK_NULL                           11
#define TK_MINUS                          12
#define TK_INTEGER                        13
#define TK_FLOAT                          14
#define TK_PLUS                           15
