#define TK_END_OF_FILE                     1
#define TK_ILLEGAL                         2
#define TK_SPACE                           3
#define TK_UNCLOSED_STRING                 4
#define TK_COMMENT                         5
#define TK_FUNCTION                        6
#define TK_COLUMN                          7
#define TK_AGG_FUNCTION                    8
#define TK_AGG_COLUMN                      9
#define TK_CONST_FUNC                     10
#define TK_SEMI                           11
#define TK_CREATE                         12
#define TK_TABLE                          13
#define TK_LP                             14
#define TK_RP                             15
#define TK_COMMA                          16
#define TK_ID                             17
#define TK_STRING                         18
#define TK_CONSTRAINT                     19
#define TK_DEFAULT                        20
#define TK_NULL                           21
#define TK_DROP                           22
#define TK_INSERT                         23
#define TK_INTO                           24
#define TK_VALUES                         25
#define TK_INTEGER                        26
#define TK_FLOAT                          27
#define TK_MINUS                          28
#define TK_PLUS                           29
